### PR TITLE
Allow file input tag return native file path

### PR DESCRIPTION
**Pull request by hokein**
Fixes atom/electron#1683.

### CODE REVIEW

**Comment by paulcbetts** [comment]
This is probably a breaking change, we probably need to somehow have developers opt-into this feature, since there is probably a ton of code that searches for `C:\Fakepath` that will now not find it

**Comment by hokein** [comment]
Thanks for the pointing. But the file `<input>` tag's behavior in nw.js also returns the native file path.

**Comment by zcbenz** [comment]
Unlike nw.js which relies on `input` tag for file dialogs, in Electron users should use the `dialog` module to open file dialogs, the `input` tag is only implemented to be compatible with traditional web pages. And as @paulcbetts said, this patch will break many web pages, so I'm closing this.

**Comment by pietrop** [comment]
@zcbenz @paulcbetts What is the future of this feature, is electron ever going to support getting a file path from HTML5` input` element (same as NWJS) ?

**Pull request closed without merging**
