### PR TITLE
Upgrade to Chrome 44.

### PR DESCRIPTION
**Pull request by hokein**
WIP

### CODE REVIEW

**Comment by frankhale** [comment]
Hi @hokein, I also performed this work last night, LOL. Were you able to get Brightray to compile against libchromiumcontent @ Chrome 44? There is a whole laundry list of issues that I saw while trying to compile it. I was going to revisit it today but if you've already patched Brightray then I may wait.

**Comment by frankhale** [comment]
I spent quite a lot of time working through the issues with Chrome 44 and Brightray but I have not fixed all the problems. Looks like a lot was changed in Chrome 44 and quite a few patches will need to be made to Brightray. I'd like to hear your thoughts on this.

**Comment by hokein** [comment]
I haven't try to build brightray yet, just pass the compliation of libchromiumcontent.

As far as I know, the upgrade working flow is:
1. Update the patch and build libchromiumcontent  successfully.
2. Update the Chromium API changes in brightray(A PR to the repository)
3. Update the Electron, and fix API changes at last.

@zcbenz maybe have a better thought.

**Comment by frankhale** [comment]
From my work I found that building libchromiumcontent was the easiest part. Additionally ffmpegsumo is now renamed to ffmpeg as far as I can tell. This requires changes to the Electron boostrap process (associated files) so that the rules to build it are created correctly instead of creating ones for ffmpegsumo. That was easy enough to fix as well. 

The problem that I am having a tough time with is the API changes in Brightray. I've managed to fix some things but it looks like some parts of the dev tools has been changed and moved into the components folder in Chromium as well as namespace changes. I have not worked out all the proper fixes to get it to compile because I am still learning how the Chromium code is layed out and it's quite confusing for me right now.

**Comment by frankhale** [comment]
Yeah it's cool, no comments are necessary. I'm probably going to continue to mess with this because it's fun and it's a great learning opportunity. If you guys end up patching Brightray before I finish that's cool as well. No worries! I can't wait to see the list of changes needed so I can gauge my progress in learning. LOL!

**Comment by zcbenz** [comment]
I usually use `script/create-dist` to create a zip archive of libchromiumcontent and use it to build electron, and merge the PR after I can confirm there is no more needs to update libchromiumcontent, because building and uploading and downloading libchromiumcontent is a very long progress.

Also electron is built against the `atom` branch of libchromiumcontent, which includes a bunch of other patches that need to be updated.

**Comment by frankhale** [comment]
Oh yeah, I figured out all of the extra patches necessary for libchromiumcontent and have documented them locally. I had no trouble updating to any of the Chromium 43 stable releases and have done so locally. Brightray also does not complain at all on any of the stable 43 releases so all is good there. 

When upgrading to Chrome 44 there are API changes that break Brightray so it needs to be patched. I wasn't able to fix all of the issues that need fixing today. It's a fun and challenging exercise though.

**Comment by frankhale** [comment]
I kind of got in the habit with my own personal Electron app to compile and rebrand my own Electron against the latest stable iojs and Chrome release (43...132 and 43...134). This allowed me an opportunity to learn a tremendous amount about Electron internals and libchromiumcontent and all the patches necessary to make it all work. It's been super fun and I hope to continue this effort.

**Comment by hokein** [comment]
@frankhale 
Thanks for your sharing information. Right now I have updated the `atom` branch' patches in my local repository [`atom-chrome44`](https://github.com/hokein/libchromiumcontent/tree/atom-chrome44), it should be compiled and created a zip(I have test on Windows).

If you are working on the upgrade on brightray, you can send a working PR to brightray to share you progress. :smile:

**Comment by frankhale** [comment]
Sure, if I am able to work out all of the changes I'd gladly send a PR for Brightray. I plan to continue effort tomorrow. I fear that I am at a disadvantage though, so much to learn and the API changes in Chrome 44 are confusing me at the moment. There are for instance some dev tools changes that have me scratching my head because they have changed quite a lot and it's requiring that I dig a lot into both Brightray and Chromium. I don't know if I will finish in time. You guys may figure it out before I do. It's okay though, I don't mind this, the fun is in the learning process.

**Comment by hokein** [comment]
@frankhale 
I have created a upgrade PR in brightray https://github.com/atom/brightray/pull/127, you can take a look on that(just pass `brightray.lib` builds).

And currently we can't build Electron due to the v8 version in Chrome 44 is 4.4 which is different with iojs v2.3(v8 4.2), we need to wait iojs v3.0.0 released with the same v8 version in Chrome 44.

**Comment by frankhale** [comment]
WOW! Thanks @hokein, I'm definitely going to look at this! Thanks for the information on V8 vs. iojs version. I think I'll try compiling your Brightray patches and Electron against a pre-release iojs 3.0 and see how it goes.

**Comment by hokein** [comment]
> I think I'll try compiling your Brightray patches and Electron against a pre-release iojs 3.0 and see how it goes.

That's great! Hope you have good progress on that! Remember to use [`atom-chrome44`](https://github.com/hokein/libchromiumcontent/tree/atom-chrome44) to build Electron.

**Comment by frankhale** [comment]
I managed to get most of the changes made to compile Electron. There are only 100 files left to compile but currently I've ran into some problems with native_mate_converters. There are issues in v8_value_converters.cc that I have not yet solved. It needs to be updated for the V8 API changes. I'll keep trying and if I make full progress then I'll let you know.

**Comment by frankhale** [comment]
Well I got it to compile but I have some link problems with unresolved symbols. LOL! 

I'm not sure how to resolve these yet because the ninja configuration is very complex and I definitely don't understand it yet. Suggestions welcome!!!

```
C:\build\electron>python script\build.py -c D
ninja: Entering directory `out\D'
[6/6] LINK_EMBED electron.exe
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True electron.exe "C:\Python27\python.exe gyp-win-tool link-wr
apper environment.x64 False link.exe /nologo /OUT:electron.exe @electron.exe.rsp" 1 mt.exe rc.exe "obj\electron.electron.exe.intermediate.mani
fest" obj\electron.electron.exe.generated.manifest ..\..\atom\browser\resources\win\atom.manifest
brightray.lib(brightray.browser_main_parts.obj) : error LNK2019: unresolved external symbol "public: __cdecl devtools_http_handler::DevToolsHt
tpHandler::~DevToolsHttpHandler(void)" (??1DevToolsHttpHandler@devtools_http_handler@@QEAA@XZ) referenced in function "public: void * __cdecl
devtools_http_handler::DevToolsHttpHandler::`scalar deleting destructor'(unsigned int)" (??_GDevToolsHttpHandler@devtools_http_handler@@QEAAPE
AXI@Z)
brightray.lib(brightray.devtools_manager_delegate.obj) : error LNK2001: unresolved external symbol "public: virtual class scoped_ptr<class net
::ServerSocket,struct base::DefaultDeleter<class net::ServerSocket> > __cdecl devtools_http_handler::DevToolsHttpHandler::ServerSocketFactory:
:CreateForHttpServer(void)" (?CreateForHttpServer@ServerSocketFactory@DevToolsHttpHandler@devtools_http_handler@@UEAA?AV?$scoped_ptr@VServerSo
cket@net@@U?$DefaultDeleter@VServerSocket@net@@@base@@@@XZ)
brightray.lib(brightray.devtools_manager_delegate.obj) : error LNK2001: unresolved external symbol "public: virtual class scoped_ptr<class net
::ServerSocket,struct base::DefaultDeleter<class net::ServerSocket> > __cdecl devtools_http_handler::DevToolsHttpHandler::ServerSocketFactory:
:CreateForTethering(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?CreateForTethering@ServerSoc
ketFactory@DevToolsHttpHandler@devtools_http_handler@@UEAA?AV?$scoped_ptr@VServerSocket@net@@U?$DefaultDeleter@VServerSocket@net@@@base@@@@PEA
V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
brightray.lib(brightray.devtools_manager_delegate.obj) : error LNK2019: unresolved external symbol "public: __cdecl devtools_http_handler::Dev
ToolsHttpHandler::DevToolsHttpHandler(class scoped_ptr<class devtools_http_handler::DevToolsHttpHandler::ServerSocketFactory,struct base::Defa
ultDeleter<class devtools_http_handler::DevToolsHttpHandler::ServerSocketFactory> >,class std::basic_string<char,struct std::char_traits<char>
,class std::allocator<char> > const &,class devtools_http_handler::DevToolsHttpHandlerDelegate *,class base::FilePath const &,class base::File
Path const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,stru
ct std::char_traits<char>,class std::allocator<char> > const &)" (??0DevToolsHttpHandler@devtools_http_handler@@QEAA@V?$scoped_ptr@VServerSock
etFactory@DevToolsHttpHandler@devtools_http_handler@@U?$DefaultDeleter@VServerSocketFactory@DevToolsHttpHandler@devtools_http_handler@@@base@@
@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVDevToolsHttpHandlerDelegate@1@AEBVFilePath@base@@311@Z) referenced in f
unction "public: static class devtools_http_handler::DevToolsHttpHandler * __cdecl brightray::DevToolsManagerDelegate::CreateHttpHandler(void)
" (?CreateHttpHandler@DevToolsManagerDelegate@brightray@@SAPEAVDevToolsHttpHandler@devtools_http_handler@@XZ)
electron.exe : fatal error LNK1120: 4 unresolved externals
Traceback (most recent call last):
  File "gyp-win-tool", line 316, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:electron.
exe @electron.exe.rsp electron.exe.manifest.res' returned non-zero exit status 1120
ninja: build stopped: subcommand failed.
```

**Comment by hokein** [comment]
@frankhale Awesome! 

The link error seems that I forgot to ship and link the devtools components. I have updated the `atom-chrome44` branch in libchromiumcontent and `chrome44` branch in brightray, you can have a try now. The link error should be removed. Thanks for your effort on building it!

**Comment by frankhale** [comment]
OH great! I will definitely revisit this today and see how things go. Thank you!

**Comment by magicae** [comment]
io.js 3.0.0 is released today, which is based on v8  4.4.63.9.

**Comment by frankhale** [comment]
I have started working on this again today because I knew io.js 3.0 was imminent. I'm compiling libchromiumcontent @ Chromium 44.0.2403.130 right now with all of the required patches that are known about. I know libchromiumcontent will compile fine, however, there are still some patches needed for Electron that I have not worked out yet. I had to comment out some code prior to get it to compile due to API changes. If I make some positive progress I wouldn't mind sharing.

**Comment by frankhale** [comment]
@hokein, FYI tools/generate_filenames_gypi.py also needs to be updated for the ffmpeg file name change.

**Comment by frankhale** [comment]
@hokein, I noticed in your fork you had two branches for Chrome 44. Thank you for fixing all the files in the patches directory. You saved me so much time! WOW!

**Comment by hokein** [comment]
@frankhale 
Glad to know v3.0.0 has been released today.

Indeed, I tried to upgrade to v3.0-apha yesterday, and have built `Electron` successfully. But I'm struggling with some crash issues in it. About the patches, I didn't upload to `atom/node` and `atom/electron` repos yet, the network card of my develop machine seems to be broken today :cry: , so I can't access internet from it recently, I hope I will fix it soon.

**Comment by frankhale** [comment]
I would love to see your Electron changes because I had to comment out some code previously to get it to compile because of some of the API changes in Chrome 44 or io.js can't remember. I have ran out of time tonight so I cannot attempt the Electron work. I did get libhchromiumcontent compiled against the 44.0.2403.130 and I have pulled iojs 3.0, just need to get some time to sit down with Electron. 

Do you have any other info on the Electron crash issues?

**Comment by frankhale** [comment]
Well I managed to compile Electron against libchromiumcontent @ Chrome 44 but it crashes immediately. This is not unexpected since there are a lot of changes that have to be made to Electron and I don't know how to fix any of them properly yet due to the iojs changes and a bunch of other things.

@hokein, thanks for the Brightray patches, those are great!

**Comment by hokein** [comment]
@frankhale I have uploaded my patches in the related repos, you can view and have a try
* The `atom-iojs-v3.0` branch in [atom/node](https://github.com/atom/node/tree/atom-iojs-v3.0).
* The `Chrome44` branch in [atom/Electron](https://github.com/atom/electron/tree/chrome44) and [atom/brightray](https://github.com/atom/brightray/tree/chrome44).
* The `atom-chrome44` branch in my fork [libchromiumcontent](https://github.com/hokein/libchromiumcontent/tree/atom-chrome44).

The crash issue still exists, and is likely caused by the failure of inject iojs in renderer process. If you comment out the  `node_bindings_->LoadEnvironment(env);` [statement](https://github.com/atom/electron/blob/chrome44/atom/renderer/atom_renderer_client.cc#L176), everything will work fine without iojs.  I'm still investigating it now, hope you make any progress on it.

**Comment by zcbenz** [comment]
I'm merging this since the compilation seems to work fine.

**Comment by frankhale** [comment]
Thanks @Hokein, the Electron changes were giving me all sorts of trouble. I'll give this a try! =)

**Comment by hokein** [comment]
@zcbenz  @frankhale 
I will go to a trip tomorrow, and will take a week leave. Here are some detailed infomation about Chrome44 on Electron side:

1. The V8IsolateMemoryDumpProvider will cause a crash in Electron startup, it looks like the  [base::ThreadTaskRunnerHandle::Get()](https://code.google.com/p/chromium/codesearch#chromium/src/gin/v8_isolate_memory_dump_provider.cc&q=V8IsolateMemoryDumpProvider&sq=package:chromium&type=cs&l=20) always return a null pointer.

2. The tricky `content::RenderViewHost::FromID(process_id, kDefaultRoutingID)` in [`GetProcessOwner`](https://github.com/atom/electron/blob/master/atom/browser/atom_browser_client.cc#L65) doesn't get the respective RVH anymore in Chrome44.

3. More infomation about the crash issue, it is caused during the period that renderer process running the `renderer/lib/init.js` period.

**Comment by zcbenz** [comment]
@hokein I'll take the work, thanks for your contributions and the information!

**Pull request merged**
