### PR TITLE
shipping ppapi components

### PR DESCRIPTION
**Pull request by deepak1556**

### CODE REVIEW

**Comment by zcbenz** [comment]
`ppapi_proxy` and `ppapi_ipc` are hard-coded to be built as shared_library, so they need to be treated specially like #104.

**Comment by hokein** [comment]
@zcbenz 
As far as I know, the `ppapi_ipc` and `ppapi_proxy` aren't hard-coded in gyp. see https://code.google.com/p/chromium/codesearch#chromium/src/ppapi/ppapi_internal.gyp&sq=package:chromium&l=81&q=%22ppapi_ipc%22&type=cs

**Comment by zcbenz** [comment]
@hokein Ah I misunderstood the code, thanks!

**Comment by deepak1556** [comment]
thanks @hokein

**Pull request merged**
