### PR TITLE
patch to provide header field with ResourceRequestDetails

### PR DESCRIPTION
**Pull request by deepak1556**
Is there any style to be followed in creating a patch file, like should the `From:` metadata be removed ? thanks!

### CODE REVIEW

**Comment by hokein** [comment]
You can use `git diff <file_name>` to generate the patch.

**Comment by deepak1556** [comment]
Fixed , thanks @hokein

**Comment by deepak1556** [comment]
@zcbenz have made the changes to provide response info.

**Comment by zcbenz** [comment]
Patch launched at https://github.com/atom/libchromiumcontent/commit/abfe09c8758d702dae60f3baa490951d55d89d2b, thanks!

**Pull request closed without merging**
