### PR TITLE
WIP: ARM build

### PR DESCRIPTION
**Pull request by zcbenz**
This is the initial work of ARM build of libchromiumcontent, it still fails for now and I don't have enough time to make it happen. Anyone who is interested in ARM build can start from here.

### CODE REVIEW

**Comment by deepak1556** [comment]
From [common.gypi](https://code.google.com/p/chromium/codesearch#chromium/src/build/common.gypi&q=common.gyp&sq=package:chromium&l=2324) setting `arm_version` sets the required compiler flags ?

**Comment by zcbenz** [comment]
> From common.gypi setting arm_version sets the required compiler flags ?

It should but it doesn't.

**Comment by zcbenz** [comment]
It seems that `standalone_static_library` is not compatible with cross-compilation, to build static_library version of ARM target we have to remove the use of `standalone_static_library` and change how we create distributions.

**Comment by zcbenz** [comment]
Actually `standalone_static_library` is compatible with cross-compilation, it is just that the static libraries generated for host toolset and target toolset have overwritten each other. I think I have found the right solution.

**Pull request merged**
